import '../styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {FC, ReactNode} from "react";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next tracker',
}

interface Props {
    children: ReactNode
}

const RootLayout: FC<Props> = ({children}) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="dark">
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
export default RootLayout
